#!/bin/bash
set -uo pipefail

# Guard against the class of bug fixed in #1305 (pipeline.config opens with
# `set -a` and its header says the matching `set +a` sits "at the end of
# this file" (#801) so every PIPELINE_* assignment crosses process
# boundaries; on the dogfood host the live file had `set +a` mid-file with
# eight knobs appended below it by hand over cycles 0-4, none of them
# exported).
#
# Dual-scan per CLAUDE.md: pipeline.config.example is always present;
# pipeline.config is gitignored and host-only (no-op in CI).

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXAMPLE="$ROOT/pipeline.config.example"
LIVE="$ROOT/pipeline.config"

PASS=0
FAIL=0
TESTS=0

pass_msg() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail_msg() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }
inc()      { TESTS=$((TESTS + 1)); }

if [ ! -f "$EXAMPLE" ]; then
  echo "ERROR: $EXAMPLE not found" >&2
  exit 1
fi

# check_tail_clean <file>
#
# Returns 0 (clean) when there is no `set -a`/`set +a` fence at all (vacuous
# pass), or when a fence exists, is balanced, and no PIPELINE_* assignment
# (commented or not) appears after the LAST `set +a`. Returns 1 (dirty) and
# prints the offending lines otherwise.
check_tail_clean() {
  local f="$1"
  local first_minus last_plus hits

  first_minus=$(grep -nE '^[[:space:]]*set[[:space:]]+-a([[:space:]]|$)' "$f" | head -1 | cut -d: -f1)
  last_plus=$(grep -nE '^[[:space:]]*set[[:space:]]+\+a([[:space:]]|$)' "$f" | tail -1 | cut -d: -f1)

  if [ -n "$first_minus" ] && [ -z "$last_plus" ]; then
    echo "    unbalanced fence: 'set -a' at line $first_minus with no matching 'set +a' in $(basename "$f")"
    return 1
  fi

  if [ -z "$last_plus" ]; then
    # No fence at all (or no set -a with no set +a already reported above) -
    # vacuously clean.
    return 0
  fi

  hits=$(awk -v b="$last_plus" \
    'NR>b && /^[[:space:]]*#?[[:space:]]*PIPELINE_[A-Z0-9_]+=/{print "    stranded: " NR": "$0}' \
    "$f")
  if [ -n "$hits" ]; then
    printf '%s\n' "$hits"
    return 1
  fi
  return 0
}

# --- Assertion A: marker on pipeline.config.example's `set +a` line only ---
#
# A host whose pipeline.config was generated by scripts/init.sh may have no
# `set +a` line at all - asserting prose against $LIVE would false-red other
# operators' hosts for wording they never wrote. The example is the one file
# we control the prose of.
inc
if grep -Eiq '^[[:space:]]*set[[:space:]]+\+a.*last line' "$EXAMPLE"; then
  pass_msg "example: set +a line carries the must-stay-last marker"
else
  fail_msg "example: set +a line lacks the must-stay-last marker"
fi

# --- Assertion B: structural dual-scan of the real files ---
inc
if check_tail_clean "$EXAMPLE"; then
  pass_msg "example: no PIPELINE_* assignment stranded after the last set +a"
else
  fail_msg "example: PIPELINE_* assignment stranded after the last set +a"
fi

if [ -f "$LIVE" ]; then
  inc
  if check_tail_clean "$LIVE"; then
    pass_msg "live: no PIPELINE_* assignment stranded after the last set +a"
  else
    fail_msg "live: PIPELINE_* assignment stranded after the last set +a"
  fi
fi

# --- Assertion C: mktemp fixture negatives + control ---
#
# Proves check_tail_clean actually bites, since B can never go red on
# already-clean real files. Never edit pipeline.config / pipeline.config.example
# in place.
FIX=""
cleanup_fix() { [ -n "$FIX" ] && rm -f "$FIX"; }
trap cleanup_fix EXIT

# c1: knob appended after the last set +a must be flagged dirty. Reuses an
# already-declared knob name (PIPELINE_HEADLESS, #1286) rather than inventing
# a new one — check_tail_clean only cares about position relative to the
# fence, not whether the name is declared elsewhere, and a novel token here
# would itself trip scripts/check-config-drift.sh's referenced-but-undeclared
# scan against this very test file.
FIX=$(mktemp)
cp "$EXAMPLE" "$FIX"
printf '%s\n' 'PIPELINE_HEADLESS="true"' >> "$FIX"
inc
if check_tail_clean "$FIX" >/dev/null; then
  fail_msg "fixture c1: knob appended after set +a was NOT flagged dirty"
else
  pass_msg "fixture c1: knob appended after set +a flagged dirty"
fi
rm -f "$FIX"

# c2: set +a stripped entirely (unbalanced fence) must be flagged dirty.
FIX=$(mktemp)
grep -vE '^[[:space:]]*set[[:space:]]+\+a([[:space:]]|$)' "$EXAMPLE" > "$FIX"
inc
if check_tail_clean "$FIX" >/dev/null; then
  fail_msg "fixture c2: set +a stripped (unbalanced fence) was NOT flagged dirty"
else
  pass_msg "fixture c2: set +a stripped (unbalanced fence) flagged dirty"
fi
rm -f "$FIX"

# c3: control - unmodified copy must be clean.
FIX=$(mktemp)
cp "$EXAMPLE" "$FIX"
inc
if check_tail_clean "$FIX" >/dev/null; then
  pass_msg "fixture c3: unmodified control is clean"
else
  fail_msg "fixture c3: unmodified control was flagged dirty"
fi
rm -f "$FIX"
FIX=""

echo ""
echo "================================"
echo "  $TESTS tests: PASS=$PASS FAIL=$FAIL"
echo "================================"

[ "$FAIL" -eq 0 ] || exit 1
